spring:
  application:
    name: deck-builder
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mtg_deck_builder_database}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  codec:
    max-in-memory-size: 50MB
